Bootstrap: docker
From: continuumio/miniconda3:master

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-bpytop
    COPYRIGHT Copyright © 2021-2022 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 1.0.68

%post
    apt update
    apt upgrade -y
    /opt/conda/bin/conda install -c conda-forge bpytop
